spring.application.name=booking
server.port=${PORT:8084}
spring.mvc.view.prefix=/WEB-INF/jspfiles/
spring.mvc.view.suffix=.jsp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/movies}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
#table creation automatically
spring.jpa.hibernate.ddl-auto=update
#what is the query execute at back end
spring.jpa.show-sql=true


