spring.application.name=booking
server.port=${PORT:8084}
spring.mvc.view.prefix=/WEB-INF/jspfiles/
spring.mvc.view.suffix=.jsp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:movies}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:vignesh2005*}
#table creation automatically
spring.jpa.hibernate.ddl-auto=update
#what is the query execute at back end
spring.jpa.show-sql=true


